language: python
sudo: false
cache: pip

python:
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install -e .

script:
  - py.test --cov-fail-under 90
  - flake8
  - radon cc --average --show-closures concierge_mako
  - radon raw --summary concierge_mako
  - radon mi --show --multi concierge_mako
  - xenon -aA -mA -bB concierge_mako

after_success:
  - codecov

notifications:
  email:
    - nineseconds@yandex.ru
